[theme]
primaryColor = "#173B57"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17202A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
